FROM node:lts-alpine AS build
WORKDIR /usr/src/app
COPY ./frontend/package.json ./
RUN npm install
COPY ./frontend/src ./src
COPY ./frontend/*.json .
RUN npm run build

FROM nginx:1.17.1-alpine
COPY ./frontend/nginx.conf /etc/nginx/nginx.conf
COPY --from=build /usr/src/app/dist/frontend /usr/share/nginx/html
