version: '3.1'
services:
  # db:
  #   image: mongo:4.2
  #   restart: always
  #   volumes:
  #     - ./data/db:/data/db
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  data_modeller:
    build:
      context: ./
      dockerfile: ./data_modeller/dockerfile
    volumes:
      - ./data/model:/myvol
    depends_on:
      - redis
  annual_balance_sheet:
    build:
      context: ./
      dockerfile: ./annual_balance_sheet/dockerfile
    depends_on:
      - redis
  annual_cash_flow:
    build:
      context: ./
      dockerfile: ./annual_cash_flow/dockerfile
    depends_on:
      - redis
  annual_income_statement:
    build:
      context: ./
      dockerfile: ./annual_income_statement/dockerfile
    depends_on:
      - redis
  daily_ohlc:
    build: 
      context: ./
      dockerfile: ./daily_ohlc/dockerfile
    depends_on:
      - redis