version: '3.1'
services:

  db: 
    image: mongo:4.2
    restart: always
    volumes:
      - ./data/db:/data/db
    ports: 
      - 27017:27017

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  back_end:
    build: 
      context: ./
      dockerfile: ./back_end/dockerfile
    ports: 
      - 3000:3000
    depends_on:
      - redis
      - db

  front_end:
    build:
      context: ./
      dockerfile: ./frontend/dockerfile
    depends_on:
      - db
      - back_end
    ports: 
      - 80:80

  data_modeller:
    build:
      context: ./
      dockerfile: ./data_modeller/dockerfile
    volumes:
      - ./data/model:/data
    depends_on:
      - redis
 
  data_processor:
    build:
      context: ./
      dockerfile: ./data_processor/dockerfile
    volumes:
      - ./data/model:/data
    depends_on:
      - redis
 
  annual_balance_sheet:
    build:
      context: ./
      dockerfile: ./annual_balance_sheet/dockerfile
    depends_on:
      - redis
 
  annual_cash_flow:
    build:
      context: ./
      dockerfile: ./annual_cash_flow/dockerfile
    depends_on:
      - redis
 
  annual_income_statement:
    build:
      context: ./
      dockerfile: ./annual_income_statement/dockerfile
    depends_on:
      - redis

  daily_ohlc:
    build: 
      context: ./
      dockerfile: ./daily_ohlc/dockerfile
    depends_on:
      - redis