version: '3.1'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  scheduler:
    image: rantony/scheduler
    depends_on:
      - redis
  annual_balance_sheet:
    image: rantony/annual_balance_sheet
    depends_on:
      - redis
  # db:
  #   image: mongo:4.2
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example