version: '3.1'
services:
  # db:
  #   image: mongo:4.2
  #   restart: always
  #   volumes:
  #     - ./data/db:/data/db
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  data_processor:
    build:
      context: ./
      dockerfile: ./data_processor/dockerfile
    depends_on:
      - redis
  # backend:
  #   image: rantony/backend
  # frontend:
  #   image: rantony/frontend
  annual_balance_sheet:
    build:
      context: ./
      dockerfile: ./annual_balance_sheet/dockerfile
    depends_on:
      - redis
      - data_processor
  annual_cash_flow:
    build:
      context: ./
      dockerfile: ./annual_cash_flow/dockerfile
    depends_on:
      - redis
      - data_processor
  annual_income_statement:
    build:
      context: ./
      dockerfile: ./annual_income_statement/dockerfile
    depends_on:
      - redis
      - data_processor
  # selenium_instance:
  #   image: selenium/standalone-chrome:102.0
  #   ports: 
  #     - 4444:4444
  # daily_ohlc:
  #   image: rantony/daily_ohlc
  #   depends_on:
  #     - selenium_instance