version: '3.1'
services:
  db:
    image: mongo:4.2
    restart: always
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  backend:
    image: rantony/backend
  frontend:
    image: rantony/frontend
  scheduler:
    image: rantony/scheduler
    depends_on:
      - redis
  annual_balance_sheet:
    image: rantony/annual_balance_sheet
    depends_on:
      - redis
  annual_cash_flow:
    image: rantony/annual_cash_flow
    depends_on:
      - redis
  annual_income_statement:
    image: rantony/annual_income_statement
    depends_on:
      - redis