FROM node:alpine
RUN mkdir /home/node/app
WORKDIR /home/node/app
COPY ./data_modeller/package.json ./
RUN npm install
COPY ./data_modeller/index.js ./
COPY ./config.json ./
VOLUME /myvol
CMD ["node", "./index.js"]
