FROM python:3.9
RUN mkdir /home/app
WORKDIR /home/app
COPY ./config.json ./
COPY ./data_modeller/requirements.txt ./
RUN pip install -r requirements.txt
COPY ./data_modeller/main.py ./
CMD ["stdbuf", "-oL", "python", "main.py"]