FROM node:alpine
RUN mkdir /home/node/app
WORKDIR /home/node/app
COPY ./data_processor/package.json ./
RUN npm install
COPY ./data_processor/index.js ./
COPY ./config.json ./
CMD ["node", "./index.js"]
