FROM node:lts-alpine AS builder
WORKDIR /app

COPY ./back_end/package.json ./
RUN npm install

COPY ./back_end ./
COPY ./config.json ./
RUN npm run build

EXPOSE 3000
CMD ["node", "dist/src/main.js"]
