FROM node:lts-alpine

RUN mkdir /home/node/app
WORKDIR /home/node/app

RUN apk update && apk add --no-cache nmap && \
    echo @edge http://nl.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories && \
    echo @edge http://nl.alpinelinux.org/alpine/edge/main >> /etc/apk/repositories && \
    apk update && \
    apk add --no-cache \
      chromium \
      harfbuzz \
      "freetype>2.8" \
      ttf-freefont \
      nss

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true

COPY ./annual_cash_flow/package.json ./
RUN npm install
EXPOSE 3000
COPY ./annual_cash_flow/index.js ./
COPY ./config.json ./
CMD ["node", "./index.js"]